const drafts = [
    {
      id: '1',
      title: 'Draft 1',
      ulbNameCode: "ULB001",
      wardNo: "10",
      isSlum: "No",
      nagarpalikaId: "NP001",
      parcelNo: "P001",
      propertyNo: "PROP001",
      electricityId: "E001",
      khasraNo: "K001",
      registryNo: "R001",
      constructedDate: "2020-01-01",
      slumId: "S001",
      respondentName: "John Doe",
      respondentRelationship: "Owner",
      ownerDetails: [
        {
          mobile: "1234567890",
          name: "John Doe",
          fatherName: "Father Doe",
          email: "john@example.com",
          landline: "0987654321",
        },
      ],
      ownerAadhaarNumber: "AADHAAR001",
      aadhaarPhoto: "photo1.jpg",
      city: "City1",
      pincode: "123456",
      houseNo: "H001",
      streetNoName: "Street 1",
      locality: "Locality 1",
      colony: "Colony 1",
      presentHouseNo: "PH001",
      presentStreetNoName: "Present Street 1",
      presentLocality: "Present Locality 1",
      presentColony: "Present Colony 1",
      presentCity: "Present City 1",
      presentPincode: "654321",
      colonyOther: "Other Colony",
      isSameAsProperty: false,
      taxRateZone: "Zone 1",
      propertyOwnership: "Owned",
      propertyOwnershipOther: "Other Ownership",
      situation: "Residential",
      situationOther: "Other Situation",
      propertyUse: "Residential",
      propertyOther: "Other Use",
      commercial: "No",
      commercialOther: "Other Commercial",
      yearOfConstruction: "2020",
      isExemptionApplicable: "No",
      exemptionType: "None",
      exemptionTypeOther: "Other Exemption",
      floors: [
        {
          floorType: "Ground",
          areaSqFt: "1000",
          areaSqMt: "93",
          usageType: "Residential",
          usageFactor: "1",
          constructionType: "Concrete",
        },
      ],
      plotAreaSqFt: "2000",
      plotAreaSqMeter: "186",
      plinthAreaSqFt: "1500",
      plinthAreaSqMeter: "139",
      totalBuiltUpAreaSqFt: "2500",
      totalBuiltUpAreaSqMeter: "232",
      isMuncipalWaterSupply: "Yes",
      toiletType: "Western",
      isMuncipalWasteService: "Yes",
      totalWaterConnection: "1",
      waterConnectionId: "WC001",
      waterConnectionType: "Metered",
      waterConnectionTypeOther: "Other Type",
      sourceOfWater: "Municipal",
      sourceOfWaterOther: "Other Source",
      propertyFirstImage: "image1.jpg",
      propertySecondImage: "image2.jpg",
      latitude: "12.9716",
      longitude: "77.5946",
      supportingDocuments: ["doc1.jpg"],
      remark: "No remarks",
    },
    {
      id: '2',
      title: 'Draft 2',
      ulbNameCode: "ULB002",
      wardNo: "20",
      isSlum: "Yes",
      nagarpalikaId: "NP002",
      parcelNo: "P002",
      propertyNo: "PROP002",
      electricityId: "E002",
      khasraNo: "K002",
      registryNo: "R002",
      constructedDate: "2019-01-01",
      slumId: "S002",
      respondentName: "Jane Doe",
      respondentRelationship: "Tenant",
      ownerDetails: [
        {
          mobile: "0987654321",
          name: "Jane Doe",
          fatherName: "Father Doe",
          email: "jane@example.com",
          landline: "1234567890",
        },
      ],
      ownerAadhaarNumber: "AADHAAR002",
      aadhaarPhoto: "photo2.jpg",
      city: "City2",
      pincode: "654321",
      houseNo: "H002",
      streetNoName: "Street 2",
      locality: "Locality 2",
      colony: "Colony 2",
      presentHouseNo: "PH002",
      presentStreetNoName: "Present Street 2",
      presentLocality: "Present Locality 2",
      presentColony: "Present Colony 2",
      presentCity: "Present City 2",
      presentPincode: "123456",
      colonyOther: "Other Colony",
      isSameAsProperty: true,
      taxRateZone: "Zone 2",
      propertyOwnership: "Rented",
      propertyOwnershipOther: "Other Ownership",
      situation: "Commercial",
      situationOther: "Other Situation",
      propertyUse: "Commercial",
      propertyOther: "Other Use",
      commercial: "Yes",
      commercialOther: "Other Commercial",
      yearOfConstruction: "2019",
      isExemptionApplicable: "Yes",
      exemptionType: "Type 1",
      exemptionTypeOther: "Other Exemption",
      floors: [
        {
          floorType: "First",
          areaSqFt: "1200",
          areaSqMt: "111",
          usageType: "Commercial",
          usageFactor: "1.2",
          constructionType: "Brick",
        },
      ],
      plotAreaSqFt: "2200",
      plotAreaSqMeter: "204",
      plinthAreaSqFt: "1600",
      plinthAreaSqMeter: "149",
      totalBuiltUpAreaSqFt: "2700",
      totalBuiltUpAreaSqMeter: "251",
      isMuncipalWaterSupply: "No",
      toiletType: "Indian",
      isMuncipalWasteService: "No",
      totalWaterConnection: "2",
      waterConnectionId: "WC002",
      waterConnectionType: "Unmetered",
      waterConnectionTypeOther: "Other Type",
      sourceOfWater: "Borewell",
      sourceOfWaterOther: "Other Source",
      propertyFirstImage: "image3.jpg",
      propertySecondImage: "image4.jpg",
      latitude: "13.0827",
      longitude: "80.2707",
      supportingDocuments: ["doc2.jpg"],
      remark: "No remarks",
    },
    {
      id: '3',
      title: 'Draft 3',
      ulbNameCode: "ULB003",
      wardNo: "30",
      isSlum: "No",
      nagarpalikaId: "NP003",
      parcelNo: "P003",
      propertyNo: "PROP003",
      electricityId: "E003",
      khasraNo: "K003",
      registryNo: "R003",
      constructedDate: "2018-01-01",
      slumId: "S003",
      respondentName: "Jim Doe",
      respondentRelationship: "Owner",
      ownerDetails: [
        {
          mobile: "1122334455",
          name: "Jim Doe",
          fatherName: "Father Doe",
          email: "jim@example.com",
          landline: "5544332211",
        },
      ],
      ownerAadhaarNumber: "AADHAAR003",
      aadhaarPhoto: "photo3.jpg",
      city: "City3",
      pincode: "789012",
      houseNo: "H003",
      streetNoName: "Street 3",
      locality: "Locality 3",
      colony: "Colony 3",
      presentHouseNo: "PH003",
      presentStreetNoName: "Present Street 3",
      presentLocality: "Present Locality 3",
      presentColony: "Present Colony 3",
      presentCity: "Present City 3",
      presentPincode: "210987",
      colonyOther: "Other Colony",
      isSameAsProperty: false,
      taxRateZone: "Zone 3",
      propertyOwnership: "Owned",
      propertyOwnershipOther: "Other Ownership",
      situation: "Industrial",
      situationOther: "Other Situation",
      propertyUse: "Industrial",
      propertyOther: "Other Use",
      commercial: "No",
      commercialOther: "Other Commercial",
      yearOfConstruction: "2018",
      isExemptionApplicable: "No",
      exemptionType: "None",
      exemptionTypeOther: "Other Exemption",
      floors: [
        {
          floorType: "Second",
          areaSqFt: "1400",
          areaSqMt: "130",
          usageType: "Industrial",
          usageFactor: "1.4",
          constructionType: "Steel",
        },
      ],
      plotAreaSqFt: "2400",
      plotAreaSqMeter: "223",
      plinthAreaSqFt: "1800",
      plinthAreaSqMeter: "167",
      totalBuiltUpAreaSqFt: "2900",
      totalBuiltUpAreaSqMeter: "269",
      isMuncipalWaterSupply: "Yes",
      toiletType: "Western",
      isMuncipalWasteService: "Yes",
      totalWaterConnection: "3",
      waterConnectionId: "WC003",
      waterConnectionType: "Metered",
      waterConnectionTypeOther: "Other Type",
      sourceOfWater: "Municipal",
      sourceOfWaterOther: "Other Source",
      propertyFirstImage: "image5.jpg",
      propertySecondImage: "image6.jpg",
      latitude: "28.7041",
      longitude: "77.1025",
      supportingDocuments: ["doc3.jpg"],
      remark: "No remarks",
    },
  ];
  
  export default drafts;